---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: swiftsend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: swiftsend
  template:
    metadata:
      labels:
        app: swiftsend
    spec:
      containers:
        - name: swiftsend
          image: swiftsend/client:latest
          ports:
            - containerPort: 3000 # Use port 3000

---
apiVersion: v1
kind: Service
metadata:
  name: swiftsend-service
spec:
  selector:
    app: swiftsend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
